version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3'
    restart: always
    container_name: 'rabbitmq'
    ports:
        - 4369:4369
        - 5671:5671
        - 5672:5672
        - 25672:25672
    environment:
      - TZ=Asia/Shanghai  
